---
- name: Instalar paquetes para PostgreSQL
  hosts: host1
  become: true
  tasks:
    - name: Instalar PostgreSQL
      yum:
        name: postgresql
        state: present
    
    - name: Inicializar PostgreSQL
      shell: /usr/pgsql-13/bin/pg_ctl start -D /var/lib/pgsql/13/data/
     
    - name: Verificar estado del servicio PostgreSQL
      systemd:
        name: postgresql
        state: started
        enabled: yes 
    
    - name: Crear base de datos
      postgresql_db:
        name: pruebas
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        owner: root
   
    - name: Crear usuario
      postgresql_user:
        name: nombre_usuario
        password: "{{ 'contraseña_encriptada' | password_hash('sha256') }}"
        login_user: usuario_administrador
        login_password: contraseña_administrador
        db: nombre_basedatos
        priv: ALL
        state: present


