---
- name: Instalar paquetes para PostgreSQL
  hosts: node1
  become: true
  tasks:
    - name: Instalar PostgreSQL
      yum:
        name: postgresql
        state: present
    
    - name: Inicializar PostgreSQL
      shell: /usr/pgsql-13/bin/pg_ctl start -D /var/lib/pgsql/13/data/
     
    - name: Verificar estado del servicio PostgreSQL
      systemd:
        name: postgresql
        state: started
        enabled: yes 
    
    - name: Crear base de datos
      postgresql_db:
        name: pruebas
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        owner: root
   
    - name: Crear usuario
      postgresql_user:
        name: pruebas
        password: "{{ 'contraseña_encriptada' | password_hash('sha256') }}"
        login_user: pruebas
        login_password: 10203040
        db: pruebas
        priv: ALL
        state: present

    - name: Habilitar acceso de usuario
      postgresql_privs:
        database: pruebas
        privs: "ALL"
        type: database
        role: pruebas
        state: present

    - name: Permitir autenticación MD5 para usuario 
      lineinfile:
        dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        regexp: "^host\\s+all\\s+{{ pruebas }}\\s+"
        line: "host    all             {{ pruebas }}             0.0.0.0/0               md5"
        state: present
        backrefs: yes
      vars:
        postgresql_version: 13  # Reemplaza con la versión correcta de PostgreSQL
        usuario: pruebas  # Reemplaza con el nombre del usuario de base de datos
    - name: Reiniciar servicio PostgreSQL
      systemd:
        name: postgresql
        state: restarted
    
    - name: Crear respaldo de base de datos postgresql
      postgresql_backup:
        dest: /tmp/backup_db/
        db: pruebas
        format: custom
        compression: yes

    - name: Reiniciar servidor
      reboot:

    - name: Cambiar hostname
      hostname:
        name: host2

    - name: Obtener IP y hostname del servidor
      gather_facts: yes

    - name: Imprimir mensaje con IP y hostname
      debug:
        msg: "La dirección IP del servidor es {{ ansible_facts['ansible_default_ipv4']['address'] }} y el hostname es {{ ansible_facts['ansible_hostname'] }}"

    - name: Agregar línea en /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.192.168.3.200 }} {{ ansible_host3 }}"
        state: present
